language: r
sudo: required
dist: trusty
cache:
  timeout: 2000
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/R/Library
warnings_are_errors: false
env:
  global:
    - R_MAX_NUM_DLLS=250
    - _R_CHECK_FORCE_SUGGESTS_="FALSE"
addons:
  apt:
    packages:
      - libgsl-dev
      - libsdl1.2-dev
      - libreadline-dev
      - imagemagick
      - libfftw3-dev
      - libudunits2-dev
      - libblas-dev
      - liblapack-dev
before_install:
 - source <( curl --insecure https://raw.githubusercontent.com/dynverse/dynmethods/master/.travis_install_python.sh ) # use travis's own python
install:
 - pip3 install --user --upgrade --only-binary=numpy,scipy numpy scipy
 - pip3 install --user --upgrade matplotlib pandas six jinja2 python-dateutil pytz pyparsing cycler tqdm python-igraph Cython statsmodels sklearn seaborn h5py anndata umap
 - R -e 'install.packages("devtools")'
 - R -e 'install.packages("knitr")'
 - R -e 'devtools::install_github(c("r-lib/rlang", "tidyverse/ggplot2"))'
 - R -e 'setRepositories(ind = 1:2); devtools::install(dep = T, upgr = T)'
script:
 - echo No R CMD check since this is an init.
r_check_args: "--no-tests --no-manual --no-vignettes --no-build-vignettes --no-examples"
r_build_args: "--no-build-vignettes"
after_success:
 - echo Init 5 succeeded!
