sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t dynalysis_base . --file scripts/base_docker/Dockerfile --build-arg GITHUB_PAT=$GITHUB_PAT
  - docker build -t dynalysis .
