language: r
sudo: required
dist: trusty
bioc_required: true
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/R
warnings_are_errors: true
python:
  - "3.6"
env:
  global:
    - R_MAX_NUM_DLLS=500
addons:
  apt:
    packages:
      - libgsl-dev
      - libsdl1.2-dev
      - libreadline-dev
      - imagemagick
      - libfftw3-dev
      - libudunits2-dev
      - libblas-dev
      - liblapack-dev
before_install:
 - sudo apt-get -y install python3-pip
 - sudo pip3 install --upgrade pip setuptools wheel
 - python3 -V
 - pip3 -V
install:
 - sudo pip3 install --upgrade --only-binary=numpy,scipy numpy scipy
 - sudo pip3 install --upgrade matplotlib pandas six jinja2 python-dateutil pytz pyparsing cycler tqdm python-igraph Cython statsmodels sklearn seaborn h5py anndata
 - R -e 'install.packages("devtools")'
 - R -e 'setRepositories(ind = 1:2)'
 - R -e 'devtools::install(dependencies = T, upgrade = T)'
