language: r
sudo: required
dist: trusty
cache: packages
warnings_are_errors: false
env:
  global:
    - R_MAX_NUM_DLLS=250
    - _R_CHECK_FORCE_SUGGESTS_="FALSE"
addons:
  apt:
    packages:
      - libgsl-dev
      - libsdl1.2-dev
      - libreadline-dev
      - imagemagick
      - libfftw3-dev
      - libudunits2-dev
      - libblas-dev
      - liblapack-dev
before_install:
 - sudo apt-get -y install python3-pip
 - sudo pip3 install --upgrade pip setuptools wheel
 - python3 -V
 - pip3 -V
install:
 - sudo pip3 install --upgrade --only-binary=numpy,scipy numpy scipy
 - sudo pip3 install --upgrade matplotlib pandas six jinja2 python-dateutil pytz pyparsing cycler tqdm python-igraph Cython statsmodels sklearn seaborn h5py anndata
 - R -e 'install.packages("devtools")'
 - R -e 'setRepositories(ind = 1:2)'
 - R -e 'devtools::install(dep = T, upgr = T)'
r_check_args: "--no-tests --no-manual --no-vignettes --no-build-vignettes"
